/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package chainofr

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    private lateinit var spamHandler: SpamHandler
    private lateinit var mail: Mail

    @Test fun appHasAGreeting() {
        val classUnderTest = App()
        assertNotNull(classUnderTest.greeting, "app should have a greeting")
    }

    @Test
    fun `Given a valid source and validate it is the same` (){
        assert(true)
        println("Happy Ending")
    }
    @Test
    fun `Using BDD`(){

        givenASpamMail()
        whenASpamReceived()
//        thenSpamMailBeenProcessed()

    }

    private fun whenASpamReceived() {

        spamHandler = SpamHandler()

    }

    private fun givenASpamMail() {
        
        mail = Mail("best buy")

    }
}
